CREATE DATABASE GERENCIADORATENDIMENTOS;

USE GERENCIADORATENDIMENTOS;

CREATE TABLE ATENDENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    NIVEL_ACESSO ENUM('admin', 'atendente') NOT NULL
);

CREATE TABLE FORMAATENDIMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE SOLICITANTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE TIPOATENDIMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SOLICITANTE_ID INT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    FOREIGN KEY (SOLICITANTE_ID) REFERENCES SOLICITANTE(ID)
);

CREATE TABLE ATENDIMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ATENDENTE_ID INT NOT NULL,
    FORMA_ATENDIMENTO_ID INT NOT NULL,
    SOLICITANTE_ID INT NOT NULL,
    TIPO_ATENDIMENTO_ID INT NOT NULL,
    DETALHES TEXT,
    DATA_HORA DATETIME NOT NULL,
    FOREIGN KEY (ATENDENTE_ID) REFERENCES ATENDENTE(ID),
    FOREIGN KEY (FORMA_ATENDIMENTO_ID) REFERENCES FORMAATENDIMENTO(ID),
    FOREIGN KEY (SOLICITANTE_ID) REFERENCES SOLICITANTE(ID),
    FOREIGN KEY (TIPO_ATENDIMENTO_ID) REFERENCES TIPOATENDIMENTO(ID)
);