CREATE DATABASE ATENDIMENTOS;

USE ATENDIMENTOS;

CREATE TABLE USUARIO(
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) DEFAULT '',
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    CARGO ENUM('usuario', 'admin') NOT NULL DEFAULT 'usuario',
    ATIVO ENUM('Ativado', 'Desativado') NOT NULL DEFAULT 'Ativado'
);

CREATE TABLE SOLICITANTE(
    ID INT PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    TIPO_PESSOA ENUM('pessoa_fisica', 'pessoa_juridica') NOT NULL,
    TIPO_SOLICITANTE VARCHAR(255) NOT NULL,
    IDENTIFICADOR_UNICO VARCHAR(255) NOT NULL,
    FORMA_ATENDIMENTO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL,
    TIPO_INFORMACAO VARCHAR(255) NOT NULL DEFAULT '',
    DESCRICAO VARCHAR(255) NOT NULL DEFAULT '',
    ATIVO ENUM('Ativado', 'Desativado') NOT NULL DEFAULT 'Ativado',
    DATA_REGISTRO_SOLI DATETIME NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE ATENDIMENTO(
    ID INT PRIMARY KEY,
    ID_SOLICITANTE INT NOT NULL,
    TIPO VARCHAR(255) NOT NULL,
    INFORMACAO VARCHAR(255) DEFAULT '',
    DATA_REGISTRO DATETIME NOT NULL,
    FOREIGN KEY (ID_SOLICITANTE) REFERENCES SOLICITANTE(ID)
);

CREATE INDEX DATA_SOLICITANTE_INDEX ON SOLICITANTE(DATA_REGISTRO_SOLI);

CREATE INDEX DATA_ATENDIMENTO_INDEX ON ATENDIMENTO(DATA_REGISTRO);

CREATE INDEX EMAIL_SOLICITANTE_INDEX ON SOLICITANTE(EMAIL);